alter table public.customers
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists telegram text,
  add column if not exists whatsapp text,
  add column if not exists email text,
  add column if not exists source text,
  add column if not exists status text default 'Новый',
  add column if not exists notes text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.vehicles
  add column if not exists vin text,
  add column if not exists lot text,
  add column if not exists year integer,
  add column if not exists make text,
  add column if not exists model text,
  add column if not exists description text,
  add column if not exists price numeric,
  add column if not exists status text default 'Рекомендуется',
  add column if not exists photos text[] default '{}',
  add column if not exists auction text,
  add column if not exists auction_url text,
  add column if not exists mileage text,
  add column if not exists damage text,
  add column if not exists fuel text,
  add column if not exists engine text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.leads
  add column if not exists customer_id bigint references public.customers(id) on delete set null,
  add column if not exists vehicle_id bigint references public.vehicles(id) on delete set null,
  add column if not exists title text,
  add column if not exists message text,
  add column if not exists status text default 'Новый',
  add column if not exists source text,
  add column if not exists budget text,
  add column if not exists next_contact_at timestamptz,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  key text not null unique,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at
before update on public.customers
for each row execute function public.set_updated_at();

drop trigger if exists vehicles_set_updated_at on public.vehicles;
create trigger vehicles_set_updated_at
before update on public.vehicles
for each row execute function public.set_updated_at();

drop trigger if exists leads_set_updated_at on public.leads;
create trigger leads_set_updated_at
before update on public.leads
for each row execute function public.set_updated_at();

drop trigger if exists site_content_set_updated_at on public.site_content;
create trigger site_content_set_updated_at
before update on public.site_content
for each row execute function public.set_updated_at();

create index if not exists customers_search_idx on public.customers using gin (
  to_tsvector('simple', coalesce(name,'') || ' ' || coalesce(phone,'') || ' ' || coalesce(telegram,'') || ' ' || coalesce(email,''))
);
create index if not exists vehicles_search_idx on public.vehicles using gin (
  to_tsvector('simple', coalesce(vin,'') || ' ' || coalesce(lot,'') || ' ' || coalesce(make,'') || ' ' || coalesce(model,''))
);
create index if not exists leads_status_idx on public.leads(status);
create index if not exists leads_customer_id_idx on public.leads(customer_id);
create index if not exists leads_vehicle_id_idx on public.leads(vehicle_id);

insert into public.site_content(key, content)
values (
  'site',
  '{
    "logo_url": "",
    "phone": "068-832-032",
    "telegram": "https://t.me/fedukusa",
    "whatsapp": "https://wa.me/37368832032",
    "hero_title": "Рассчитайте полную стоимость автомобиля до Кишинева",
    "hero_text": "Цена покупки автомобиля, аукционные сборы, доставка, страховка, таможенные платежи и сопровождение сделки — в одном понятном расчете.",
    "benefits": [
      "Подбор и проверка лота",
      "Расчет стоимости под ключ",
      "Участие в торгах",
      "Документы, доставка и сопровождение"
    ]
  }'::jsonb
)
on conflict (key) do nothing;
